parameter_sets:
  - message_str: "The quick brown fox jumps over the lazy dog"
    mult_amp: 0.2
    rx_mix_freq: -12000
    tx_mix_freq: 12000
    tx_rx_bw: 5000
    tx_cr: 1
    tx_rx_sf: 7
    tx_rx_sync_word: [18]

  - message_str: "The quick brown fox jumps over the lazy dog"
    mult_amp: 0.15
    rx_mix_freq: -12000
    tx_mix_freq: 12000
    tx_rx_bw: 5000
    tx_cr: 1
    tx_rx_sf: 7
    tx_rx_sync_word: [18]

  - message_str: "The quick brown fox jumps over the lazy dog"
    mult_amp: 0.1
    rx_mix_freq: -12000
    tx_mix_freq: 12000
    tx_rx_bw: 5000
    tx_cr: 1
    tx_rx_sf: 7
    tx_rx_sync_word: [18]

  - message_str: "The quick brown fox jumps over the lazy dog"
    mult_amp: 0.2
    rx_mix_freq: -12000
    tx_mix_freq: 12000
    tx_rx_bw: 5000
    tx_cr: 1
    tx_rx_sf: 8
    tx_rx_sync_word: [18]

  - message_str: "The quick brown fox jumps over the lazy dog"
    mult_amp: 0.15
    rx_mix_freq: -12000
    tx_mix_freq: 12000
    tx_rx_bw: 5000
    tx_cr: 1
    tx_rx_sf: 8
    tx_rx_sync_word: [18]

  - message_str: "The quick brown fox jumps over the lazy dog"
    mult_amp: 0.1
    rx_mix_freq: -12000
    tx_mix_freq: 12000
    tx_rx_bw: 5000
    tx_cr: 1
    tx_rx_sf: 8
    tx_rx_sync_word: [18]

  - message_str: "The quick brown fox jumps over the lazy dog"
    mult_amp: 0.2
    rx_mix_freq: -12000
    tx_mix_freq: 12000
    tx_rx_bw: 5000
    tx_cr: 1
    tx_rx_sf: 9
    tx_rx_sync_word: [18]

  - message_str: "The quick brown fox jumps over the lazy dog"
    mult_amp: 0.15
    rx_mix_freq: -12000
    tx_mix_freq: 12000
    tx_rx_bw: 5000
    tx_cr: 1
    tx_rx_sf: 9
    tx_rx_sync_word: [18]

  - message_str: "The quick brown fox jumps over the lazy dog"
    mult_amp: 0.1
    rx_mix_freq: -12000
    tx_mix_freq: 12000
    tx_rx_bw: 5000
    tx_cr: 1
    tx_rx_sf: 9
    tx_rx_sync_word: [18]

# BW is 5000 for all
# CR is same for all (4/5, which corresponds to 1 in the source code)
# sync word is same for all (default 18)
# mix frequency is 12000 +/- for all (center freq)
# message string is same for all