parameter_sets:
  - message_str: "The quick brown fox jumps over the lazy dog"
    mult_amp: 0.2
    rx_mix_freq: -12000
    tx_mix_freq: 12000
    tx_rx_bw: 5000
    tx_cr: 0
    tx_rx_sf: 7
    tx_rx_sync_word: [18]

  - message_str: "TEST"
    mult_amp: 0.2
    rx_mix_freq: -12000
    tx_mix_freq: 12000
    tx_rx_bw: 5000
    tx_cr: 0
    tx_rx_sf: 7
    tx_rx_sync_word: [18]

  - message_str: "The underwater modem transmitted chirped acoustic signals across the lakebed, enabling reliable communication between autonomous vehicles exploring submerged environments with minimal packet loss."
    mult_amp: 0.2
    rx_mix_freq: -12000
    tx_mix_freq: 12000
    tx_rx_bw: 5000
    tx_cr: 0
    tx_rx_sf: 7
    tx_rx_sync_word: [18]

    # BW is 5000 for all
    # CR is same for all
    # sync word is same for all (default 18)
    # mix frequency is 12000 +/- for all (center freq)